{
 "title": "airlab-dash",
 "tags": [ "airlab" ],
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Latest Reading",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawQueryText": "SELECT\n  CAST(strftime('%s', timestamp) AS INTEGER) * 1000 AS last_updated,\n  pressure_hpa, temperature_c, humidity_percent, co2_ppm, voc_index, nox_index\nFROM airlab_readings\nORDER BY timestamp DESC\nLIMIT 1\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "rawQueryText": "SELECT\n  CAST(strftime('%s', timestamp) AS INTEGER) AS time,\n  co2_ppm\nFROM airlab_readings\nORDER BY timestamp\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawQueryText": "SELECT\n  CAST(strftime('%s', timestamp) AS INTEGER) AS time,\n  temperature_c\nFROM airlab_readings\nORDER BY timestamp\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "rawQueryText": "SELECT\n  CAST(strftime('%s', timestamp) AS INTEGER) AS time,\n  pressure_hpa\nFROM airlab_readings\nORDER BY timestamp\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawQueryText": "SELECT\n  CAST(strftime('%s', timestamp) AS INTEGER) AS time,\n  humidity_percent\nFROM airlab_readings\nORDER BY timestamp\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "VOC Index",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 27 },
   "targets": [
    {
     "rawQueryText": "SELECT\n  CAST(strftime('%s', timestamp) AS INTEGER) AS time,\n  voc_index\nFROM airlab_readings\nORDER BY timestamp\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "NOx Index",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 27 },
   "targets": [
    {
     "rawQueryText": "SELECT\n  CAST(strftime('%s', timestamp) AS INTEGER) AS time,\n  nox_index\nFROM airlab_readings\nORDER BY timestamp\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}